export const players = [
  {
    id: "497f6eca-6276-4993-bfeb-53cbbbba6f08",
    nom: "Amougou",
    prenom: "Bellinga",
    sexe: "MASCULIN",
    date: "2000/01/02",
    lieu_naissance: "Nkoabang",
    residence: "Fandena ",
    poids: 85,
    taille: 186,
    envergure: 200,
    telephone: "699990000",
    dossard: 10,
    email: "amougou.belinga@gmail.com",
    annee_inscription: 2020,
    classe_frequentee: "maternelle",
    date_naissance: "1980/01/02",
    main_forte: "GAUCHE",
    reseaux_sociaux: [
      {
        key: "facebook",
        value: "amougou.belinga",
      },
    ],
    nom_etablissement: "vison4",
    nom_parent_1: "Amougou Cesard",
    telephone_parent_1: "699991111",
    nom_parent_2: "inconnu",
    telephone_parent_2: "688881111",
    statut: "BROUILLON",
    ligue: "OUEST",
    post: "Meneur",
    club: "firebird",
  },
];
